const ids=['cameraInput','preview','ocrStatus','cardNameInput','searchButton','suggestions','resultsCard','resultsTitle','results','finishFilter','collectionList','collectionSearch','exportButton','totalCards','uniqueCards','totalValue','addDialog','dialogImage','dialogName','dialogSet','dialogFinish','dialogCondition','dialogQuantity','dialogLocation','dialogPrice','confirmAdd','soundToggle','resultTemplate','cameraVideo','captureCanvas','startScanner','stopScanner','scannerBadge','scanFlash','cameraPlaceholder','lastDetection','quickQuantity'];
const els=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
let currentPrintings=[],selectedPrinting=null,stream=null,scanTimer=null,scanning=false,processing=false,resumeAfterDialog=false,lastDetected='',lastDetectedAt=0;
let fastMode=JSON.parse(localStorage.getItem('mtg-fast-mode')??'false');
let soundEnabled=JSON.parse(localStorage.getItem('mtg-sound-enabled')??'true');
let inventory=JSON.parse(localStorage.getItem('mtg-inventory')??'[]');
const fmtEUR=v=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(v||0));
const safeText=v=>(v??'').toString();
function setScannerState(state,text){els.scannerBadge.className=`scanner-badge ${state}`;els.scannerBadge.textContent=text;}
function saveInventory(){localStorage.setItem('mtg-inventory',JSON.stringify(inventory));renderCollection();renderStats();}
function getImage(card){return card.image_uris?.normal||card.card_faces?.[0]?.image_uris?.normal||'';}
function getArt(card){return card.image_uris?.art_crop||card.card_faces?.[0]?.image_uris?.art_crop||getImage(card);}
function availableFinishes(card){const out=[];if(card.nonfoil)out.push({key:'nonfoil',label:'Normale',price:Number(card.prices?.eur||card.prices?.usd||0)});if(card.foil)out.push({key:'foil',label:'Foil',price:Number(card.prices?.eur_foil||card.prices?.usd_foil||0)});if(card.finishes?.includes('etched'))out.push({key:'etched',label:'Etched',price:Number(card.prices?.eur_etched||card.prices?.usd_etched||0)});return out.length?out:[{key:'nonfoil',label:'Normale',price:Number(card.prices?.eur||card.prices?.usd||0)}];}
async function startCamera(){if(stream)return;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});els.cameraVideo.srcObject=stream;await els.cameraVideo.play();els.cameraPlaceholder.classList.add('hidden');els.startScanner.classList.add('hidden');els.stopScanner.classList.remove('hidden');scanning=true;setScannerState('active',fastMode?'Rapide':'En attente');els.ocrStatus.textContent='Présente une carte entière, bien droite et sans reflet.';scheduleNextScan(500);}catch(err){console.error(err);setScannerState('error','Caméra refusée');els.ocrStatus.textContent='Impossible d’ouvrir la caméra. Vérifie l’autorisation caméra dans Safari.';}}
function stopCamera(){scanning=false;processing=false;clearTimeout(scanTimer);stream?.getTracks().forEach(t=>t.stop());stream=null;els.cameraVideo.srcObject=null;els.cameraPlaceholder.classList.remove('hidden');els.startScanner.classList.remove('hidden');els.stopScanner.classList.add('hidden');setScannerState('idle','Arrêté');els.ocrStatus.textContent='Caméra arrêtée.';}
function scheduleNextScan(delay=1000){clearTimeout(scanTimer);if(scanning&&!processing)scanTimer=setTimeout(scanCurrentFrame,delay);}
function captureFullCard(){const v=els.cameraVideo;if(!v.videoWidth||!v.videoHeight)return null;const c=els.captureCanvas,scale=Math.min(1,900/v.videoWidth);c.width=Math.round(v.videoWidth*scale);c.height=Math.round(v.videoHeight*scale);c.getContext('2d',{willReadFrequently:true}).drawImage(v,0,0,c.width,c.height);return c;}
function makeRegion(source,x,y,w,h,scale=1.5,filter='grayscale(1) contrast(1.8)'){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w*scale));c.height=Math.max(1,Math.round(h*scale));const ctx=c.getContext('2d',{willReadFrequently:true});ctx.filter=filter;ctx.drawImage(source,x,y,w,h,0,0,c.width,c.height);return c;}
function cleanOCRLines(text){return text.split(/\r?\n/).map(s=>s.replace(/[^A-Za-z0-9À-ÿ',.\-: /]/g,' ').replace(/\s+/g,' ').trim()).filter(Boolean);}
function extractSignals(titleText,bottomText){const titleLines=cleanOCRLines(titleText).filter(s=>s.length>=2&&s.length<=50),bottomLines=cleanOCRLines(bottomText);const joinedBottom=bottomLines.join(' '),matches=joinedBottom.match(/(?:^|\s)(\d{1,4}[A-Za-z]?)\s*\/\s*(\d{1,4})/g)||[];const collectorNumbers=[...new Set(matches.map(v=>v.match(/(\d{1,4}[A-Za-z]?)/)?.[1]).filter(Boolean))];const setCodes=[...new Set((joinedBottom.match(/\b[A-Z0-9]{3,5}\b/g)||[]).filter(v=>!/^(WOTC|ILLUS|ARTIST)$/i.test(v)).map(v=>v.toLowerCase()))];const languageHints=[];const joined=`${titleText} ${bottomText}`;if(/[À-ÿ]/.test(joined))languageHints.push('fr');if(/©|Wizards|Illustrated by|Illus\./i.test(joined))languageHints.push('en');return{titleCandidates:titleLines.slice(0,6),collectorNumbers,setCodes,rawBottom:bottomLines.slice(0,8),languageHints};}
async function recognizeFrame(canvas){const w=canvas.width,h=canvas.height,titleRegion=makeRegion(canvas,w*.12,h*.07,w*.76,h*.16,2),bottomRegion=makeRegion(canvas,w*.07,h*.70,w*.86,h*.26,1.8);const [title,bottom]=await Promise.all([Tesseract.recognize(titleRegion,'eng+fra'),Tesseract.recognize(bottomRegion,'eng+fra')]);return extractSignals(title.data.text,bottom.data.text);}
async function findCandidates(signals){for(const title of signals.titleCandidates.slice(0,3)){const r=await fetch(`https://api.scryfall.com/cards/named?fuzzy=${encodeURIComponent(title)}`);if(!r.ok)continue;const base=await r.json(),cards=[];let next=base.prints_search_uri;while(next){const p=await fetch(next);if(!p.ok)break;const d=await p.json();cards.push(...(d.data||[]));next=d.has_more?d.next_page:null;}if(cards.length)return{base,candidates:cards};}return null;}
function baseScore(card,s){let score=0;const collector=String(card.collector_number||'').toLowerCase();if(s.collectorNumbers.some(n=>collector===String(n).toLowerCase()))score+=85;else if(s.collectorNumbers.some(n=>collector.startsWith(String(n).toLowerCase())))score+=38;if(s.setCodes.includes(String(card.set||'').toLowerCase()))score+=60;if(s.languageHints.includes(card.lang))score+=12;if(card.frame_effects?.length)score+=3;if(card.promo)score-=2;return score;}
function cropObservedArt(frame){const w=frame.width,h=frame.height;return makeRegion(frame,w*.16,h*.20,w*.68,h*.39,0.45,'none');}
function descriptorFromCanvas(canvas){const c=document.createElement('canvas');c.width=16;c.height=16;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(canvas,0,0,16,16);const data=ctx.getImageData(0,0,16,16).data,gray=[],hist=new Array(24).fill(0);for(let i=0;i<data.length;i+=4){const r=data[i],g=data[i+1],b=data[i+2];gray.push((r+g+b)/3);hist[Math.min(7,Math.floor(r/32))]++;hist[8+Math.min(7,Math.floor(g/32))]++;hist[16+Math.min(7,Math.floor(b/32))]++;}const avg=gray.reduce((a,b)=>a+b,0)/gray.length;return{hash:gray.map(v=>v>avg?1:0),hist:hist.map(v=>v/256)};}
function descriptorDistance(a,b){let h=0;for(let i=0;i<a.hash.length;i++)if(a.hash[i]!==b.hash[i])h++;let color=0;for(let i=0;i<a.hist.length;i++)color+=Math.abs(a.hist[i]-b.hist[i]);return(h/a.hash.length)*.72+(color/a.hist.length)*.28;}
async function loadImageDescriptor(url){return new Promise((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{try{const c=document.createElement('canvas');c.width=180;c.height=130;c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(descriptorFromCanvas(c));}catch(e){reject(e);}};img.onerror=reject;img.src=url;});}
async function visualRank(cards,signals,frame){const observed=descriptorFromCanvas(cropObservedArt(frame));const shortlist=cards.map(card=>({card,score:baseScore(card,signals)})).sort((a,b)=>b.score-a.score).slice(0,fastMode?10:24);await Promise.all(shortlist.map(async item=>{try{const d=await loadImageDescriptor(getArt(item.card));const similarity=Math.max(0,1-descriptorDistance(observed,d));item.visual=Math.round(similarity*100);item.score+=Math.round(similarity*95);}catch{item.visual=0;}}));return shortlist.sort((a,b)=>b.score-a.score||new Date(b.card.released_at)-new Date(a.card.released_at));}
async function scanCurrentFrame(){if(!scanning||processing||els.addDialog.open)return;processing=true;setScannerState('processing','Analyse');els.ocrStatus.textContent='Nom, numéro, symbole et illustration en cours d’analyse…';try{const frame=captureFullCard();if(!frame)throw new Error('Image indisponible');const signals=await recognizeFrame(frame);if(!signals.titleCandidates.length){els.ocrStatus.textContent='Aucun nom lisible. Rapproche la carte.';return;}const found=await findCandidates(signals);if(!found){els.ocrStatus.textContent=`Lecture incertaine : ${signals.titleCandidates[0]}`;return;}const now=Date.now();if(found.base.name===lastDetected&&now-lastDetectedAt<4500){els.ocrStatus.textContent=`${found.base.name} déjà détectée. Présente une autre carte.`;return;}lastDetected=found.base.name;lastDetectedAt=now;const ranked=await visualRank(found.candidates,signals,frame);currentPrintings=ranked.map(r=>r.card);els.cardNameInput.value=found.base.name;els.resultsTitle.textContent=`${found.base.name} — meilleures correspondances`;els.resultsCard.classList.remove('hidden');renderResults(ranked);els.scanFlash.classList.add('visible');setTimeout(()=>els.scanFlash.classList.remove('visible'),350);navigator.vibrate?.(80);const best=ranked[0],confidence=Math.min(99,Math.round((best?.score||0)/2));els.lastDetection.classList.remove('hidden');els.lastDetection.innerHTML=`<strong>${safeText(found.base.name)}</strong><span>${signals.collectorNumbers.length?`n° ${safeText(signals.collectorNumbers.join(', '))} · `:''}${signals.setCodes.length?`${safeText(signals.setCodes.join(', ').toUpperCase())} · `:''}illustration ${best?.visual||0}% · confiance ${confidence}%</span>`;els.ocrStatus.textContent='Version la plus probable trouvée.';resumeAfterDialog=true;if((best?.score||0)>=120||(fastMode&&(best?.score||0)>=85))openAddDialog(best.card,true);else els.resultsCard.scrollIntoView({behavior:'smooth',block:'start'});}catch(err){console.error(err);els.ocrStatus.textContent='Analyse impossible. Maintiens la carte stable.';}finally{processing=false;if(scanning&&!els.addDialog.open){setScannerState('active',fastMode?'Rapide':'En attente');scheduleNextScan(fastMode?600:1100);}}}
async function runOCR(file){els.preview.src=URL.createObjectURL(file);els.preview.classList.remove('hidden');els.ocrStatus.textContent='Analyse complète de la photo…';const img=new Image();img.src=els.preview.src;await img.decode();const c=els.captureCanvas,scale=Math.min(1,1200/img.naturalWidth);c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const signals=await recognizeFrame(c),found=await findCandidates(signals);if(!found){els.ocrStatus.textContent='Carte non reconnue.';return;}const ranked=await visualRank(found.candidates,signals,c);currentPrintings=ranked.map(r=>r.card);els.cardNameInput.value=found.base.name;els.resultsTitle.textContent=`${found.base.name} — meilleures correspondances`;els.resultsCard.classList.remove('hidden');renderResults(ranked);}
async function searchCard(name){name=(name||els.cardNameInput.value).trim();if(!name)return;els.searchButton.disabled=true;els.searchButton.textContent='Recherche…';els.resultsCard.classList.remove('hidden');els.results.innerHTML='<p class="muted">Recherche de toutes les impressions…</p>';try{const exact=await fetch(`https://api.scryfall.com/cards/named?fuzzy=${encodeURIComponent(name)}`);if(!exact.ok)throw new Error();const base=await exact.json(),cards=[];let next=base.prints_search_uri;while(next){const p=await fetch(next),d=await p.json();cards.push(...(d.data||[]));next=d.has_more?d.next_page:null;}currentPrintings=cards;els.resultsTitle.textContent=`${base.name} — ${cards.length} versions`;renderResults();}catch{els.results.innerHTML='<p class="muted">Carte introuvable.</p>';}finally{els.searchButton.disabled=false;els.searchButton.textContent='Rechercher';}}
function renderResults(ranked=null){const filter=els.finishFilter.value,scores=new Map((ranked||[]).map(r=>[r.card.id,r]));const cards=currentPrintings.filter(c=>filter==='all'||availableFinishes(c).some(f=>f.key===filter));if(!ranked)cards.sort((a,b)=>new Date(b.released_at)-new Date(a.released_at));els.results.innerHTML='';for(const card of cards){const node=els.resultTemplate.content.cloneNode(true),img=node.querySelector('img');img.src=getImage(card);img.alt=`${card.name}, ${card.set_name}`;node.querySelector('h3').textContent=card.set_name;const rank=scores.get(card.id);node.querySelector('.set-line').textContent=`${card.released_at?.slice(0,4)||''} · n° ${card.collector_number}${rank?` · score ${rank.score}`:''}`;node.querySelector('.variant-line').textContent=[...availableFinishes(card).map(f=>f.label),card.lang?.toUpperCase(),rank?.visual?`illustration ${rank.visual}%`:null].filter(Boolean).join(' · ');const prices=availableFinishes(card).map(f=>f.price).filter(v=>v>0);node.querySelector('.price').textContent=prices.length?`Dès ${fmtEUR(Math.min(...prices))}`:'Prix indisponible';node.querySelector('button').onclick=()=>openAddDialog(card,false);els.results.appendChild(node);}if(!cards.length)els.results.innerHTML='<p class="muted">Aucune version.</p>';}
function openAddDialog(card,automatic=false){selectedPrinting=card;resumeAfterDialog=scanning;clearTimeout(scanTimer);els.dialogImage.src=getImage(card);els.dialogName.textContent=card.name;els.dialogSet.textContent=`${card.set_name} · n° ${card.collector_number}${automatic?' · meilleure correspondance':''}`;els.dialogFinish.innerHTML=availableFinishes(card).map(f=>`<option value="${f.key}" data-price="${f.price}">${f.label}</option>`).join('');els.dialogQuantity.value=Math.max(1,Number(els.quickQuantity?.value||1));els.dialogLocation.value='';updateDialogPrice();els.addDialog.showModal();}
function updateDialogPrice(){const opt=els.dialogFinish.selectedOptions[0],price=Number(opt?.dataset.price||0),qty=Math.max(1,Number(els.dialogQuantity.value||1));els.dialogPrice.textContent=price?fmtEUR(price*qty):'Indisponible';}
function addSelected(){const opt=els.dialogFinish.selectedOptions[0],finish=opt.value,unitPrice=Number(opt.dataset.price||0),qty=Math.max(1,Number(els.dialogQuantity.value||1)),key=`${selectedPrinting.id}-${finish}-${els.dialogCondition.value}-${els.dialogLocation.value.trim()}`;const existing=inventory.find(i=>i.key===key);if(existing)existing.quantity+=qty;else inventory.push({key,scryfallId:selectedPrinting.id,name:selectedPrinting.name,setName:selectedPrinting.set_name,setCode:selectedPrinting.set,collectorNumber:selectedPrinting.collector_number,image:getImage(selectedPrinting),finish,finishLabel:opt.textContent,condition:els.dialogCondition.value,location:els.dialogLocation.value.trim(),quantity:qty,unitPrice,addedAt:new Date().toISOString()});saveInventory();playValueSound(unitPrice);els.addDialog.close();els.ocrStatus.textContent=`${selectedPrinting.name} ajoutée. Présente la suivante.`;if(resumeAfterDialog&&scanning){setScannerState('active',fastMode?'Rapide':'En attente');scheduleNextScan(fastMode?450:800);}}
function renderCollection(){const q=els.collectionSearch.value.toLowerCase().trim(),items=inventory.filter(i=>`${i.name} ${i.setName} ${i.location}`.toLowerCase().includes(q));els.collectionList.innerHTML='';if(!items.length){els.collectionList.innerHTML='<p class="muted">Aucune carte enregistrée.</p>';return;}items.sort((a,b)=>(b.unitPrice*b.quantity)-(a.unitPrice*a.quantity));for(const item of items){const row=document.createElement('article');row.className='collection-item';row.innerHTML=`<img src="${item.image}" alt="${safeText(item.name)}"><div><h3>${safeText(item.name)}</h3><p>${safeText(item.setName)} · n° ${safeText(item.collectorNumber)}</p><p>${safeText(item.finishLabel)} · ${safeText(item.condition)} · quantité ${item.quantity}</p>${item.location?`<p>📍 ${safeText(item.location)}</p>`:''}<button class="delete-btn">Supprimer</button></div><div class="value">${item.unitPrice?fmtEUR(item.unitPrice*item.quantity):'—'}</div>`;row.querySelector('.delete-btn').onclick=()=>{if(confirm('Supprimer cette entrée ?')){inventory=inventory.filter(i=>i.key!==item.key);saveInventory();}};els.collectionList.appendChild(row);}}
function renderStats(){els.totalCards.textContent=inventory.reduce((s,i)=>s+i.quantity,0);els.uniqueCards.textContent=inventory.length;els.totalValue.textContent=fmtEUR(inventory.reduce((s,i)=>s+i.unitPrice*i.quantity,0));}
function playValueSound(value){if(!soundEnabled)return;const ctx=new(window.AudioContext||window.webkitAudioContext)(),now=ctx.currentTime,seq=value<1?[[520,.05,.08]]:value<5?[[520,0,.10],[660,.14,.12]]:value<20?[[440,0,.10],[554,.13,.10],[660,.26,.15]]:[[440,0,.09],[554,.11,.09],[660,.22,.09],[880,.34,.22]];seq.forEach(([freq,offset,dur],idx)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=value>=20?'triangle':'sine';osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,now+offset);gain.gain.exponentialRampToValueAtTime(Math.min(.3,.1+idx*.04),now+offset+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+offset+dur);osc.connect(gain);gain.connect(ctx.destination);osc.start(now+offset);osc.stop(now+offset+dur+.02);});}
function exportCSV(){const headers=['Nom','Extension','Code','Numéro','Finition','État','Quantité','Emplacement','Prix unitaire EUR','Valeur totale EUR'],rows=inventory.map(i=>[i.name,i.setName,i.setCode,i.collectorNumber,i.finishLabel,i.condition,i.quantity,i.location,i.unitPrice,i.unitPrice*i.quantity]),csv=[headers,...rows].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='inventaire-mtg.csv';a.click();URL.revokeObjectURL(a.href);}
els.startScanner.onclick=startCamera;els.stopScanner.onclick=stopCamera;els.cameraInput.onchange=e=>e.target.files[0]&&runOCR(e.target.files[0]);els.searchButton.onclick=()=>searchCard();els.cardNameInput.addEventListener('keydown',e=>{if(e.key==='Enter')searchCard();});els.finishFilter.onchange=()=>renderResults();els.dialogFinish.onchange=updateDialogPrice;els.dialogQuantity.oninput=updateDialogPrice;els.confirmAdd.onclick=addSelected;els.collectionSearch.oninput=renderCollection;els.exportButton.onclick=exportCSV;els.soundToggle.onclick=()=>{soundEnabled=!soundEnabled;localStorage.setItem('mtg-sound-enabled',JSON.stringify(soundEnabled));els.soundToggle.textContent=soundEnabled?'🔊':'🔇';};els.soundToggle.textContent=soundEnabled?'🔊':'🔇';document.querySelectorAll('.rail-btn').forEach(btn=>{if(btn.textContent.includes('Rapide')){btn.classList.toggle('active',fastMode);btn.onclick=()=>{fastMode=!fastMode;localStorage.setItem('mtg-fast-mode',JSON.stringify(fastMode));btn.classList.toggle('active',fastMode);setScannerState(scanning?'active':'idle',scanning?(fastMode?'Rapide':'En attente'):'Arrêté');};}});els.addDialog.addEventListener('close',()=>{if(resumeAfterDialog&&scanning){setScannerState('active',fastMode?'Rapide':'En attente');scheduleNextScan(fastMode?450:800);}});document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===tab));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===tab.dataset.target));});window.addEventListener('pagehide',stopCamera);if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');renderCollection();renderStats();